//===- GMP.td - GMP dialect definition ----------------------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef GMP_TD
#define GMP_TD

// Dialect
include "GMPDialect.td"
// Attributes
include "GMPAttributes.td"
// Types
include "GMPTypes.td"
// Operations
include "GMPOps.td"

#endif // GMP_TD
